# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lfk < Formula
  desc "Lightning Fast Kubernetes navigator - keyboard-focused TUI for managing K8s clusters"
  homepage "https://github.com/janosmiko/lfk"
  version "0.6.0"
  license "MIT"

  depends_on "helm" => :optional
  depends_on "kubectl" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/janosmiko/lfk/releases/download/v0.6.0/lfk_0.6.0_darwin_amd64.zip"
      sha256 "9cb49d3690a58fd6f53068f468f07495b4a6f041ba70a2aab511916d503ccb03"

      define_method(:install) do
        bin.install "lfk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/janosmiko/lfk/releases/download/v0.6.0/lfk_0.6.0_darwin_arm64.zip"
      sha256 "ab4bae23a229defcbaabfbd2f6db1793af88393055deffaed4465671d28b1647"

      define_method(:install) do
        bin.install "lfk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/janosmiko/lfk/releases/download/v0.6.0/lfk_0.6.0_linux_amd64.tar.gz"
      sha256 "b3f28f9d3d52de19c811f6910a43d3fd3e1936461a9bd5865b5c1b8c85fc7513"
      define_method(:install) do
        bin.install "lfk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/janosmiko/lfk/releases/download/v0.6.0/lfk_0.6.0_linux_arm64.tar.gz"
      sha256 "95f4b2ed16959436c30e4e97fd89dcf2b389049831cccfcaf1efff304adf953b"
      define_method(:install) do
        bin.install "lfk"
      end
    end
  end

  test do
    system "#{bin}/lfk", "--version"
  end
end
