# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HetznerK3s < Formula
  desc "This is a CLI tool to quickly create and manage Kubernetes clusters in Hetzner Cloud using the lightweight Kubernetes distribution k3s from Rancher."
  homepage ""
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/janosmiko/hetzner-k3s/releases/download/v0.1.0/hetzner-k3s_Darwin_arm64.tar.gz"
      sha256 "885215e848aa94c863e1752a14bf2de5012d016a6b17e6759c5006e4109e5e81"

      def install
        bin.install "hetzner-k3s"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/janosmiko/hetzner-k3s/releases/download/v0.1.0/hetzner-k3s_Darwin_x86_64.tar.gz"
      sha256 "efec15bacca431458b02e9f35b33bbf361cbc14d795592b2a0a3e35cbdfc27c1"

      def install
        bin.install "hetzner-k3s"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/janosmiko/hetzner-k3s/releases/download/v0.1.0/hetzner-k3s_Linux_aarch64.tar.gz"
      sha256 "2f2e9c8fbd873aa325893c4f105984bd04087e08aa0f6ea3fd0ca4ac079a21b5"

      def install
        bin.install "hetzner-k3s"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/janosmiko/hetzner-k3s/releases/download/v0.1.0/hetzner-k3s_Linux_x86_64.tar.gz"
      sha256 "cec6e0e76f2a9a2aebcc0dc4c2532c614419af7d85d09608aaefb5d7a75bf472"

      def install
        bin.install "hetzner-k3s"
      end
    end
  end

  depends_on "kubectl" => :required
end
