# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HetznerK3s < Formula
  desc "This is a CLI tool to quickly create and manage Kubernetes clusters in Hetzner Cloud using the lightweight Kubernetes distribution k3s from Rancher."
  homepage ""
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/janosmiko/hetzner-k3s/releases/download/v0.1.0/hetzner-k3s_Darwin_arm64.tar.gz"
      sha256 "f549d5a66bdd0e05e0176801bd9fed123cdaee08b040c194c1aab9ac6dd1745f"

      def install
        bin.install "hetzner-k3s"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/janosmiko/hetzner-k3s/releases/download/v0.1.0/hetzner-k3s_Darwin_x86_64.tar.gz"
      sha256 "7a9cfdd603c87c11f8b2edcad900821d6ca01ff070add7342b7ad98ca555e28f"

      def install
        bin.install "hetzner-k3s"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/janosmiko/hetzner-k3s/releases/download/v0.1.0/hetzner-k3s_Linux_aarch64.tar.gz"
      sha256 "f175fd27529c97d0885370a44f6bc2bdda9d2d1df9806eb02189e568cd6d53b2"

      def install
        bin.install "hetzner-k3s"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/janosmiko/hetzner-k3s/releases/download/v0.1.0/hetzner-k3s_Linux_x86_64.tar.gz"
      sha256 "9b38cc37419c892f6764e79365ee539ca184afafb8104399865bf6df56f39c45"

      def install
        bin.install "hetzner-k3s"
      end
    end
  end

  depends_on "kubectl" => :required
end
