# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HetznerK3s < Formula
  desc "This is a CLI tool to quickly create and manage Kubernetes clusters in Hetzner Cloud using the lightweight Kubernetes distribution k3s from Rancher."
  homepage ""
  version "0.1.6"
  license "MIT"

  depends_on "kubectl" => :required

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/janosmiko/hetzner-k3s/releases/download/v0.1.6/hetzner-k3s_Darwin_arm64.tar.gz"
      sha256 "c6a7a1fd7deb30276f334b947575126be8fe22bcca24d43931b4633b2fc250e4"

      def install
        bin.install "hetzner-k3s"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/janosmiko/hetzner-k3s/releases/download/v0.1.6/hetzner-k3s_Darwin_x86_64.tar.gz"
      sha256 "a0a40f6e1860adb3a2e1fec9ca86d889991bcf44690f013735ed14c37d287434"

      def install
        bin.install "hetzner-k3s"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/janosmiko/hetzner-k3s/releases/download/v0.1.6/hetzner-k3s_Linux_aarch64.tar.gz"
      sha256 "9619b56523970ec105f8b0daf758beedf771180b45511b069c41150700e32b65"

      def install
        bin.install "hetzner-k3s"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/janosmiko/hetzner-k3s/releases/download/v0.1.6/hetzner-k3s_Linux_x86_64.tar.gz"
      sha256 "f926af5b6d417a4c3c6ea8321b907c455e4dc7727c8ab20002b9143e367ad060"

      def install
        bin.install "hetzner-k3s"
      end
    end
  end
end
