# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LfkNightly < Formula
  desc "Lightning Fast Kubernetes navigator (nightly) - keyboard-focused TUI for managing K8s clusters"
  homepage "https://github.com/janosmiko/lfk"
  version "0.10.0-nightly.202604172256"
  license "MIT"

  depends_on "helm" => :optional
  depends_on "kubectl" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/janosmiko/lfk/releases/download/v0.10.0-nightly.202604172256/lfk_0.10.0-nightly.202604172256_darwin_amd64.zip"
      sha256 "0da18c08a7220eab108e19b51694f51709e0a74eaf0b224f7dd9e68beff1fc5c"

      define_method(:install) do
        bin.install "lfk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/janosmiko/lfk/releases/download/v0.10.0-nightly.202604172256/lfk_0.10.0-nightly.202604172256_darwin_arm64.zip"
      sha256 "78ec3a4f87c35f9f1b41178144e8033bb232bdca9b75148e50bd37b64545a050"

      define_method(:install) do
        bin.install "lfk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/janosmiko/lfk/releases/download/v0.10.0-nightly.202604172256/lfk_0.10.0-nightly.202604172256_linux_amd64.tar.gz"
      sha256 "e4927cc7475c9d01e65cc038776cf62c33586a0a1ac1156dcb1afad18e1fb54d"
      define_method(:install) do
        bin.install "lfk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/janosmiko/lfk/releases/download/v0.10.0-nightly.202604172256/lfk_0.10.0-nightly.202604172256_linux_arm64.tar.gz"
      sha256 "05835888082ef76bb7a0979c43d1de0a45886c34a5fce522b8be3d4086b86b2a"
      define_method(:install) do
        bin.install "lfk"
      end
    end
  end

  test do
    system "#{bin}/lfk", "--version"
  end
end
