# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LfkNightly < Formula
  desc "Lightning Fast Kubernetes navigator (nightly) - keyboard-focused TUI for managing K8s clusters"
  homepage "https://github.com/janosmiko/lfk"
  version "0.10.0-nightly.202604181425"
  license "MIT"

  depends_on "helm" => :optional
  depends_on "kubectl" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/janosmiko/lfk/releases/download/v0.10.0-nightly.202604181425/lfk_0.10.0-nightly.202604181425_darwin_amd64.zip"
      sha256 "a2581d04e6d85526fcf72cbaf145b306703c93aabe81524f3e070a69a1b6d272"

      define_method(:install) do
        bin.install "lfk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/janosmiko/lfk/releases/download/v0.10.0-nightly.202604181425/lfk_0.10.0-nightly.202604181425_darwin_arm64.zip"
      sha256 "936d420830e6607ef5808293ab9d6494cf328d845755b20f0e5485de78a3f734"

      define_method(:install) do
        bin.install "lfk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/janosmiko/lfk/releases/download/v0.10.0-nightly.202604181425/lfk_0.10.0-nightly.202604181425_linux_amd64.tar.gz"
      sha256 "f2fcbb26ca65ae9acbd581980c9f82033a84675d3dec6c26520c107bae553e88"
      define_method(:install) do
        bin.install "lfk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/janosmiko/lfk/releases/download/v0.10.0-nightly.202604181425/lfk_0.10.0-nightly.202604181425_linux_arm64.tar.gz"
      sha256 "d1cbb5b33f1b3749b0826b3efa95a4823fc72fd91867ffc32430cf5f58a3c50b"
      define_method(:install) do
        bin.install "lfk"
      end
    end
  end

  test do
    system "#{bin}/lfk", "--version"
  end
end
