# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LfkNightly < Formula
  desc "Lightning Fast Kubernetes navigator (nightly) - keyboard-focused TUI for managing K8s clusters"
  homepage "https://github.com/janosmiko/lfk"
  version "0.10.0-nightly.202604200710"
  license "MIT"

  depends_on "helm" => :optional
  depends_on "kubectl" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/janosmiko/lfk/releases/download/v0.10.0-nightly.202604200710/lfk_0.10.0-nightly.202604200710_darwin_amd64.zip"
      sha256 "fd5bd63f17592dd808bafa4517a778737bbe6e5cdfb80f6b4979c000464a0539"

      define_method(:install) do
        bin.install "lfk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/janosmiko/lfk/releases/download/v0.10.0-nightly.202604200710/lfk_0.10.0-nightly.202604200710_darwin_arm64.zip"
      sha256 "cbf4993ce0ddca059cf727616d13e5f7c8b0690069619184057413de0e7b26a4"

      define_method(:install) do
        bin.install "lfk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/janosmiko/lfk/releases/download/v0.10.0-nightly.202604200710/lfk_0.10.0-nightly.202604200710_linux_amd64.tar.gz"
      sha256 "4431fed63f4eea76278a6305108f23e81dfcdce0ae28f13bea77248f398b5a9c"
      define_method(:install) do
        bin.install "lfk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/janosmiko/lfk/releases/download/v0.10.0-nightly.202604200710/lfk_0.10.0-nightly.202604200710_linux_arm64.tar.gz"
      sha256 "a5ee2dc0aa44dd1b9bf33e4fdabe20bf2b19cfbb617437b3a9a42c0220b76e0a"
      define_method(:install) do
        bin.install "lfk"
      end
    end
  end

  test do
    system "#{bin}/lfk", "--version"
  end
end
