# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lfk < Formula
  desc "Lightning Fast Kubernetes navigator - keyboard-focused TUI for managing K8s clusters"
  homepage "https://github.com/janosmiko/lfk"
  version "0.14.19"
  license "Apache-2.0"

  depends_on "helm" => :optional
  depends_on "kubectl" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/janosmiko/lfk/releases/download/v0.14.19/lfk_0.14.19_darwin_amd64.zip"
      sha256 "f510c31afdacfd10a50815998410260faa3d5cfff59b6d0c1a7f86d6cdf7e3bb"

      define_method(:install) do
        bin.install "lfk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/janosmiko/lfk/releases/download/v0.14.19/lfk_0.14.19_darwin_arm64.zip"
      sha256 "75c1db303714575b23b187499201ce314c440faadfacb104f758e5e89d0c1a7f"

      define_method(:install) do
        bin.install "lfk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/janosmiko/lfk/releases/download/v0.14.19/lfk_0.14.19_linux_amd64.tar.gz"
      sha256 "c75262597803579be2c8775366ee5e4e66aa8d21b4e2b2f40b26a1bbb84a00db"
      define_method(:install) do
        bin.install "lfk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/janosmiko/lfk/releases/download/v0.14.19/lfk_0.14.19_linux_arm64.tar.gz"
      sha256 "f4012f0ffffb9f26078a672d4ed52b3aba0ddad2b13514d228381f258c0db1db"
      define_method(:install) do
        bin.install "lfk"
      end
    end
  end

  test do
    system "#{bin}/lfk", "--version"
  end
end
