# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lfk < Formula
  desc "Lightning Fast Kubernetes navigator - keyboard-focused TUI for managing K8s clusters"
  homepage "https://github.com/janosmiko/lfk"
  version "0.14.12"
  license "Apache-2.0"

  depends_on "helm" => :optional
  depends_on "kubectl" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/janosmiko/lfk/releases/download/v0.14.12/lfk_0.14.12_darwin_amd64.zip"
      sha256 "40c185197224770922bf6cd3abd7856451def905731f7e46c475d089d0702f77"

      define_method(:install) do
        bin.install "lfk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/janosmiko/lfk/releases/download/v0.14.12/lfk_0.14.12_darwin_arm64.zip"
      sha256 "97d2ada1384b13c4d1a8c6c91d3a48198ea23a02f5e39cf077d635938b29e0fb"

      define_method(:install) do
        bin.install "lfk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/janosmiko/lfk/releases/download/v0.14.12/lfk_0.14.12_linux_amd64.tar.gz"
      sha256 "bbeaf09658380ce10af319c6f6e296fb940200ecbb82d6d622ab6632ddc9d8dd"
      define_method(:install) do
        bin.install "lfk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/janosmiko/lfk/releases/download/v0.14.12/lfk_0.14.12_linux_arm64.tar.gz"
      sha256 "561e41b70c7eebd53b4c07b9626e87422e8a13fb7851417285c9bf867fe61b32"
      define_method(:install) do
        bin.install "lfk"
      end
    end
  end

  test do
    system "#{bin}/lfk", "--version"
  end
end
