# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lfk < Formula
  desc "Lightning Fast Kubernetes navigator - keyboard-focused TUI for managing K8s clusters"
  homepage "https://github.com/janosmiko/lfk"
  version "0.13.2"
  license "Apache-2.0"

  depends_on "helm" => :optional
  depends_on "kubectl" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/janosmiko/lfk/releases/download/v0.13.2/lfk_0.13.2_darwin_amd64.zip"
      sha256 "6e0e3b61cb694487f8f36f372867d8d197f1307e4898e25f4f39336c508c0c18"

      define_method(:install) do
        bin.install "lfk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/janosmiko/lfk/releases/download/v0.13.2/lfk_0.13.2_darwin_arm64.zip"
      sha256 "c6ef69a39752fb6223780f9eea36a8001bc0a8cda76e866e697e678b1dcf64fb"

      define_method(:install) do
        bin.install "lfk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/janosmiko/lfk/releases/download/v0.13.2/lfk_0.13.2_linux_amd64.tar.gz"
      sha256 "23f8b9a3af0652e1c0e64c18cb07511d1614999c24a304857ac177e92643ecae"
      define_method(:install) do
        bin.install "lfk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/janosmiko/lfk/releases/download/v0.13.2/lfk_0.13.2_linux_arm64.tar.gz"
      sha256 "d2b6bc9b265b2325c62374e6b162b63d072f9f45a9ee9ff39397de38bcb04425"
      define_method(:install) do
        bin.install "lfk"
      end
    end
  end

  test do
    system "#{bin}/lfk", "--version"
  end
end
