# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vau < Formula
  desc "A terminal UI for browsing HashiCorp Vault"
  homepage "https://github.com/janosmiko/vau"
  version "0.6.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/janosmiko/vau/releases/download/v0.6.2/vau_0.6.2_darwin_amd64.zip"
      sha256 "05ce4c543bc568c944f460b48f6466d97a0778f3f6677c6ff39d4eceb3649fef"

      define_method(:install) do
        bin.install "vau"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/janosmiko/vau/releases/download/v0.6.2/vau_0.6.2_darwin_arm64.zip"
      sha256 "011532612af92351acdccdffdb8b1178bc8a0ab8d5fb3d7fb2edc8f5f4e37ac5"

      define_method(:install) do
        bin.install "vau"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/janosmiko/vau/releases/download/v0.6.2/vau_0.6.2_linux_amd64.tar.gz"
      sha256 "078bb3ae28b5373f7f77acb108ddaf2e1c328ff3fbc7631335dd9897339ba97b"
      define_method(:install) do
        bin.install "vau"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/janosmiko/vau/releases/download/v0.6.2/vau_0.6.2_linux_arm64.tar.gz"
      sha256 "51046b2d6e1e80eb05ec597c5562feda70e067c908f3bc3a87c344dcdcd7323e"
      define_method(:install) do
        bin.install "vau"
      end
    end
  end

  test do
    system "#{bin}/vau", "--version"
  end
end
