# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vau < Formula
  desc "A terminal UI for browsing HashiCorp Vault"
  homepage "https://github.com/janosmiko/vau"
  version "0.6.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/janosmiko/vau/releases/download/v0.6.3/vau_0.6.3_darwin_amd64.zip"
      sha256 "3abc5154b9b3b9f63ca4f387f7005ff7c313262eb789c047094f0280a43c03a6"

      define_method(:install) do
        bin.install "vau"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/janosmiko/vau/releases/download/v0.6.3/vau_0.6.3_darwin_arm64.zip"
      sha256 "7553c3481b93d4ee489690f41c820b9c97e89c800c3967b18166a818cc6606b3"

      define_method(:install) do
        bin.install "vau"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/janosmiko/vau/releases/download/v0.6.3/vau_0.6.3_linux_amd64.tar.gz"
      sha256 "ebf10696e32c2efc1486a4262fd8932682f612f19930f3ef4ead4dfc268c1063"
      define_method(:install) do
        bin.install "vau"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/janosmiko/vau/releases/download/v0.6.3/vau_0.6.3_linux_arm64.tar.gz"
      sha256 "dc82c7e87b788e52ce591ad23c5d547332c79c13448a386800cfaf8d5750c5a0"
      define_method(:install) do
        bin.install "vau"
      end
    end
  end

  test do
    system "#{bin}/vau", "--version"
  end
end
